#!/usr/bin/env node
/**
 * fuzz-data.js
 *
 * Reads a generated data-*.ts file, applies fuzzLocation to every project's
 * coordinates, and writes a companion *-fuzzed.ts file for use on the public map.
 *
 * Seeds are derived from each project's id so pins are stable across runs
 * (same id → same offset every time). See fuzzLocation.ts for details.
 *
 * Usage:
 *   node src/utility/fuzz-data.js
 *
 * If the output file already exists, appends -1, -2, … until a free name is found.
 */

import fs   from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);

// ── File paths ────────────────────────────────────────────────────────────────
const INPUT_TS      = path.resolve(__dirname, '../data/private/data-20260331.ts');
const OUTPUT_TS_BASE = path.resolve(__dirname, '../data/private/data-20260331-fuzzed.ts');

// ── Fuzzing parameters (mirror defaults from fuzzLocation.ts) ─────────────────
const EARTH_RADIUS_KM  = 6371;
const FUZZ_RADIUS_MIN_KM = 1.0;
const FUZZ_RADIUS_MAX_KM = 2.0;

// ── Resolve a non-colliding output path ───────────────────────────────────────
function resolveOutputPath(basePath) {
  if (!fs.existsSync(basePath)) return basePath;
  const ext  = path.extname(basePath);
  const stem = basePath.slice(0, -ext.length);
  let n = 1;
  while (true) {
    const candidate = `${stem}-${n}${ext}`;
    if (!fs.existsSync(candidate)) return candidate;
    n++;
  }
}

// ── Seeded PRNG (mulberry32 — mirrors fuzzLocation.ts) ───────────────────────
function makeSeededRng(seed) {
  let h = 0x9e3779b9;
  for (let i = 0; i < seed.length; i++) {
    h = Math.imul(h ^ seed.charCodeAt(i), 0x85ebca6b);
    h ^= h >>> 13;
  }
  let state = h >>> 0;
  return function mulberry32() {
    state |= 0;
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 0x100000000;
  };
}

function fuzzLocation(lat, lng, seed) {
  const rng    = makeSeededRng(seed);
  const minSq  = FUZZ_RADIUS_MIN_KM * FUZZ_RADIUS_MIN_KM;
  const maxSq  = FUZZ_RADIUS_MAX_KM * FUZZ_RADIUS_MAX_KM;
  const r      = Math.sqrt(minSq + rng() * (maxSq - minSq));
  const theta  = rng() * 2 * Math.PI;

  const deltaLat = (r * Math.cos(theta)) / EARTH_RADIUS_KM * (180 / Math.PI);
  const deltaLng = (r * Math.sin(theta)) /
    (EARTH_RADIUS_KM * Math.cos(lat * (Math.PI / 180))) *
    (180 / Math.PI);

  const fLat = Math.max(-90, Math.min(90, lat + deltaLat));
  let   fLng = lng + deltaLng;
  if (fLng >  180) fLng -= 360;
  if (fLng < -180) fLng += 360;

  return { lat: fLat, lng: fLng };
}

// ── Parse the TS data file ────────────────────────────────────────────────────
// Extract id, lat, lng per entry using simple regex — no need to eval the file.
const src = fs.readFileSync(INPUT_TS, 'utf8');

// Match each project block: capture id and location
const ENTRY_RE = /id:\s*(\d+)[\s\S]*?location:\s*\{\s*lat:\s*(-?[\d.]+),\s*lng:\s*(-?[\d.]+)\s*\}/g;

const fuzzMap = new Map(); // id → { lat, lng }
let match;
while ((match = ENTRY_RE.exec(src)) !== null) {
  const id  = parseInt(match[1], 10);
  const lat = parseFloat(match[2]);
  const lng = parseFloat(match[3]);
  // Seed per project: stable across regenerations of this file
  const seed = `agromap:${id}`;
  fuzzMap.set(id, fuzzLocation(lat, lng, seed));
}

if (fuzzMap.size === 0) {
  console.error('No entries found in input file — check the path or format.');
  process.exit(1);
}

// ── Rewrite location fields in source ────────────────────────────────────────
// Replace each `location: { lat: X, lng: Y }` with the fuzzed values.
// We iterate by id so we can look up the right fuzzed coords.
let out = src;

// Replace header comment
out = out.replace(
  /\/\/ Auto-generated by .*\n\/\/ Source:.*\n\/\/ Date:.*\n/,
  [
    `// Auto-generated by src/utility/fuzz-data.js`,
    `// Source: ${path.relative(path.dirname(OUTPUT_TS_BASE), INPUT_TS)}`,
    `// Date:   ${new Date().toISOString()}`,
    `// Coordinates fuzzed [${FUZZ_RADIUS_MIN_KM}, ${FUZZ_RADIUS_MAX_KM}] km annulus — seeds: agromap:<id>`,
    ``,
  ].join('\n')
);

// Replace each location block, matching by surrounding id context
out = out.replace(
  /(id:\s*(\d+)[\s\S]*?)(location:\s*\{\s*lat:\s*-?[\d.]+,\s*lng:\s*-?[\d.]+\s*\})/g,
  (full, prefix, idStr, _locBlock) => {
    const id = parseInt(idStr, 10);
    const f  = fuzzMap.get(id);
    if (!f) return full;
    return `${prefix}location: { lat: ${f.lat}, lng: ${f.lng} }`;
  }
);

// ── Write output ──────────────────────────────────────────────────────────────
const OUTPUT_TS = resolveOutputPath(OUTPUT_TS_BASE);
fs.writeFileSync(OUTPUT_TS, out, 'utf8');

console.log(`Fuzzed  ${fuzzMap.size} locations  [${FUZZ_RADIUS_MIN_KM}–${FUZZ_RADIUS_MAX_KM} km annulus]`);
console.log(`Written → ${OUTPUT_TS}`);
