import { AgroEcologyProject } from './types';

export const projects: AgroEcologyProject[] = [
  {
    id: 1,
    name: "Eastern Cape Initiative A",
    category: 'LS',
    contact: "Contact A",
    province: "Eastern Cape",
    district: "Amathole",
    nearestTown: "Butterworth",
    location: { lat: -32.47, lng: 28.19 },
    yearStarted: 2016,
    highOnFarmDiversity: true,
    mixedFarming: true,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: true,
    onSiteTraining: true,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: true,
    gsMarketingServices: false,
  },
  {
    id: 2,
    name: "Eastern Cape Initiative B",
    category: 'CC',
    contact: "Contact B",
    province: "Eastern Cape",
    district: "Amathole",
    nearestTown: "King William's Town",
    location: { lat: -32.73, lng: 27.23 },
    yearStarted: 2016,
    highOnFarmDiversity: false,
    mixedFarming: true,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: true,
    structuredTrainingProgrammes: true,
    trainingType: 'S I',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: true,
    gsMarketingServices: true,
  },
  {
    id: 3,
    name: "Eastern Cape Initiative C",
    category: 'AEH',
    contact: "Contact C",
    province: "Eastern Cape",
    district: "Buffalo City Metropolitan Municipality",
    nearestTown: "East London",
    location: { lat: -33.04, lng: 27.41 },
    yearStarted: 2015,
    highOnFarmDiversity: true,
    mixedFarming: false,
    seedBankIndividual: false,
    seedBankCollective: true,
    organisedSeedExchange: true,
    integratedLandscapeManagement: false,
    onSiteTraining: true,
    structuredTrainingProgrammes: true,
    trainingType: 'S I L',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: true,
    gsMarketingServices: true,
  },
];
