import { AgroEcologyProject } from './types';

export const projects: AgroEcologyProject[] = [
  {
    id: 1,
    name: "Eastern Cape Initiative A",
    category: 'LS',
    contact: "Contact A",
    province: "Eastern Cape",
    district: "Amathole",
    nearestTown: "Butterworth",
    location: { lat: -32.47, lng: 28.19 },
    yearStarted: 2016,
    highOnFarmDiversity: true,
    mixedFarming: true,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: true,
    onSiteTraining: true,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: true,
    gsMarketingServices: false,
  },
  {
    id: 2,
    name: "Eastern Cape Initiative B",
    category: 'CC',
    contact: "Contact B",
    province: "Eastern Cape",
    district: "Amathole",
    nearestTown: "King William's Town",
    location: { lat: -32.73, lng: 27.23 },
    yearStarted: 2016,
    highOnFarmDiversity: false,
    mixedFarming: true,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: true,
    structuredTrainingProgrammes: true,
    trainingType: 'S I',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: true,
    gsMarketingServices: true,
  },
  {
    id: 3,
    name: "Eastern Cape Initiative C",
    category: 'AEH',
    contact: "Contact C",
    province: "Eastern Cape",
    district: "Buffalo City Metropolitan Municipality",
    nearestTown: "East London",
    location: { lat: -33.04, lng: 27.41 },
    yearStarted: 2015,
    highOnFarmDiversity: true,
    mixedFarming: false,
    seedBankIndividual: false,
    seedBankCollective: true,
    organisedSeedExchange: true,
    integratedLandscapeManagement: false,
    onSiteTraining: true,
    structuredTrainingProgrammes: true,
    trainingType: 'S I L',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: true,
    gsMarketingServices: true,
  },

  // ── Cluster test data: KwaNyuswa, KZN ────────────────────────────────────
  // 10 tightly clustered real-world entries (~metres apart in source data).
  // Origins below are FICTITIOUS — shifted ~15 km NW to avoid exposing real
  // coordinates in the public repo. Fuzzing test only.
  {
    id: 4,
    name: "KwaNyuswa LS 1",
    category: 'LS',
    contact: "Contact KZN-1",
    province: "KwaZulu-Natal",
    district: "Ugu",
    nearestTown: "Harding",
    location: { lat: -30.52, lng: 29.93 },
    yearStarted: 2020,
    highOnFarmDiversity: false,
    mixedFarming: false,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: false,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: false,
    gsMarketingServices: false,
  },
  {
    id: 5,
    name: "KwaNyuswa LS 2",
    category: 'LS',
    contact: "Contact KZN-2",
    province: "KwaZulu-Natal",
    district: "Ugu",
    nearestTown: "Harding",
    location: { lat: -30.52, lng: 29.93 },
    yearStarted: 2022,
    highOnFarmDiversity: false,
    mixedFarming: true,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: false,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: true,
    gsMarketingServices: false,
  },
  {
    id: 6,
    name: "KwaNyuswa LS 3",
    category: 'LS',
    contact: "Contact KZN-3",
    province: "KwaZulu-Natal",
    district: "Ugu",
    nearestTown: "Harding",
    location: { lat: -30.52, lng: 29.93 },
    yearStarted: 2014,
    highOnFarmDiversity: false,
    mixedFarming: true,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: false,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: false,
    gsMarketingServices: false,
  },
  {
    id: 7,
    name: "KwaNyuswa LS 4",
    category: 'LS',
    contact: "Contact KZN-4",
    province: "KwaZulu-Natal",
    district: "Ugu",
    nearestTown: "Harding",
    location: { lat: -30.52, lng: 29.93 },
    yearStarted: 2015,
    highOnFarmDiversity: false,
    mixedFarming: true,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: true,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: true,
    gsMarketingServices: false,
  },
  {
    id: 8,
    name: "KwaNyuswa LS 5",
    category: 'LS',
    contact: "Contact KZN-5",
    province: "KwaZulu-Natal",
    district: "Ugu",
    nearestTown: "Harding",
    location: { lat: -30.52, lng: 29.93 },
    yearStarted: 2021,
    highOnFarmDiversity: false,
    mixedFarming: false,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: true,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: true,
    gsMarketingServices: false,
  },
  {
    id: 9,
    name: "KwaNyuswa LS 6",
    category: 'LS',
    contact: "Contact KZN-6",
    province: "KwaZulu-Natal",
    district: "Ugu",
    nearestTown: "Harding",
    location: { lat: -30.52, lng: 29.93 },
    yearStarted: 2022,
    highOnFarmDiversity: false,
    mixedFarming: false,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: false,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: false,
    gsMarketingServices: false,
  },
  {
    id: 10,
    name: "KwaNyuswa LS 7",
    category: 'LS',
    contact: "Contact KZN-7",
    province: "KwaZulu-Natal",
    district: "Ugu",
    nearestTown: "Harding",
    location: { lat: -30.52, lng: 29.93 },
    yearStarted: 2015,
    highOnFarmDiversity: false,
    mixedFarming: true,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: false,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: false,
    gsMarketingServices: false,
  },
  {
    id: 11,
    name: "KwaNyuswa LS 8",
    category: 'LS',
    contact: "Contact KZN-8",
    province: "KwaZulu-Natal",
    district: "Ugu",
    nearestTown: "Izingolweni",
    location: { lat: -30.52, lng: 29.93 },
    yearStarted: 2015,
    highOnFarmDiversity: false,
    mixedFarming: false,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: false,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: false,
    gsMarketingServices: false,
  },
  {
    id: 12,
    name: "KwaNyuswa LS 9",
    category: 'LS',
    contact: "Contact KZN-9",
    province: "KwaZulu-Natal",
    district: "Ugu",
    nearestTown: "Izingolweni",
    location: { lat: -30.52, lng: 29.93 },
    yearStarted: 2023,
    highOnFarmDiversity: false,
    mixedFarming: false,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: false,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: false,
    gsMarketingServices: false,
  },
  {
    id: 13,
    name: "KwaNyuswa LS 10",
    category: 'LS',
    contact: "Contact KZN-10",
    province: "KwaZulu-Natal",
    district: "Ugu",
    nearestTown: "Izingolweni",
    location: { lat: -30.52, lng: 29.93 },
    yearStarted: 2014,
    highOnFarmDiversity: false,
    mixedFarming: false,
    seedBankIndividual: false,
    seedBankCollective: false,
    organisedSeedExchange: false,
    integratedLandscapeManagement: false,
    onSiteTraining: true,
    structuredTrainingProgrammes: false,
    trainingType: '',
    trainingAccreditation: false,
    gsInputSupply: true,
    gsMentorshipTechSupport: true,
    gsMarketingServices: false,
  },
  // ─────────────────────────────────────────────────────────────────────────
];
